default_stages:
  - commit
repos:
- repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
  rev: v8.0.0
  hooks:
    - id: commitlint
      stages: [commit-msg]
      additional_dependencies: ["@commitlint/config-conventional"]
- repo: https://github.com/zricethezav/gitleaks
  rev: v8.5.0
  hooks:
    - id: gitleaks
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/golangci/golangci-lint
  rev: v1.45.0
  hooks:
    - id: golangci-lint
      verbose: true
